apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  labels:
     order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
     order-service-app
  template:
    metadata:
      labels:
       order-service-app
    spec:
      containers:
        - name : order-service-app
          image:  sudhavenkatachalam/order-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
   order-service-svc
spec:
  ports:
    - targetPort: 8082
      port: 80
  selector:
   order-service-app