apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service-app
  labels:
      restaurant-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      restaurant-service-app
  template:
    metadata:
      labels:
        restaurant-service-app
    spec:
      containers:
        - name : restaurant-service-app
          image:  sudhavenkatachalam/restaurant-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  nrestaurant-service-svc
spec:
  ports:
    - targetPort: 8081
      port: 80
  selector:
    restaurant-service-app